default:
  image: ${CI_REGISTRY}/android/shared/docker-android/oci-ndk:v2.0.0
  before_script:
    - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - publish

build library:
  stage: build
  tags:
    - shared-large
  script:
    - ./gradlew :tunnel:assembleRelease
  artifacts:
    expire_in: 1 week
    paths:
      - tunnel/build/outputs/aar/

publish library:
  stage: publish
  tags:
    - shared-large
  when: manual
  only:
    - /^release\/.+$/
  script:
    - ./gradlew publish

sync-wireguard-android:
  stage: publish
  only:
    refs:
      - /^release\/.*/
  before_script:
    - !reference [ default, before_script ]
    - apt update && apt-get install -y connect-proxy
  script:
    - git clone "$CI_REPOSITORY_URL" --branch "$CI_COMMIT_BRANCH" _APP_CLONE;
    - cd _APP_CLONE
    - git remote add public git@github.com:ProtonVPN/wireguard-android.git
    - git push public "$CI_COMMIT_BRANCH" -f

sync-go:
  stage: publish
  only:
    refs:
      - /^release\/.*/
  variables:
    OPENSOURCE_GO: "true"
  trigger:
    project: ProtonVPN/development/wireguard-go
    branch: release/android
