default:
  image: ${CI_REGISTRY}/android/shared/docker-android/ndk:v1.0.0
  before_script:
    - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - publish

build library:
  stage: build
  tags:
    - large
  script:
    - ./gradlew :tunnel:assembleRelease
  artifacts:
    expire_in: 1 week
    paths:
      - tunnel/build/outputs/aar/

publish library:
  stage: publish
  tags:
    - small
  when: manual
  only:
    - /^release\/.+$/
  script:
    - ./gradlew publish
